// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using agenciaGoTour.Data;

#nullable disable

namespace agenciaGoTour.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107193642_addimagens")]
    partial class addimagens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("agenciaGoTour.Model.Destinos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Imagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Litoral do estado do Ceará, Região Nordeste do país. Principal ponto turístico: Beach Park.",
                            Imagem = "https://www.alemdaenergia.engie.com.br/uploads/2020/06/aquiraz-cidade-inteligente.jpg",
                            Nome = "Aquiraz"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Litoral sudeste. Diversidade e beleza paisagística. Principal ponto turístico: Pão de Açúcar, Cristo Redentor.",
                            Imagem = "https://revistaazul.voeazul.com.br/wp-content/uploads/2023/03/muito-alem-da-praia-saiba-o-que-fazer-no-rio-de-janeiro.jpeg",
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Serra Gaúcha. Beleza com ruas floridas, repletas. Arquitetura bávara. Ótimos para momentos a dois e em família. ",
                            Imagem = "https://media.gazetadopovo.com.br/2022/09/17194513/Gramado-tem-atrativos-o-ano-inteiro.-Vale-a-pena-conhecer-cada-pedaC3A7o-da-cidade-seja-qual-for-a-C3A9poca-da-sua-viagem.-960x540.jpg",
                            Nome = "Gramado"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Um dos lugares mais intensos e incríveis da Argentina. Lugares como impressionantes, lagos, arroios, rios de degelo e montanhas.",
                            Imagem = "https://escapemagazine.com.br/wp-content/uploads/2023/08/winter-night-esqui-em-bariloche.jpg",
                            Nome = "Bariloche"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
